package com.lingua.lingua;

import android.os.Bundle;
import android.util.Log;

import androidx.annotation.Nullable;
import androidx.appcompat.app.AppCompatActivity;


public class VideoCallActivity extends AppCompatActivity {


    private final static String TAG = "VideoCallActivity";

    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_video_call);
        // print the token generated by the VideoTokenGenerator
        VideoTokenGenerator tokenGenerator = new VideoTokenGenerator();
        if (tokenGenerator.token == null) {
            Log.d(TAG, "Token object not generated");
        } else {
            Log.d(TAG, "Token generated");
        }
    }
}
